
name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: 20.62.252.50
        username: azureuser
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/azureuser/app
          git pull origin main
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          npm install
          pm2 restart far-alpha-api || pm2 start index.js --name far-alpha-api
